/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config wrangler.toml --include-runtime false` (hash: 4f02f348f24120ae3f4f102bd109be74)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		KV: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
