/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config wrangler.toml --include-runtime false` (hash: 4f02f348f24120ae3f4f102bd109be74)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		KV: KVNamespace;
		/**
		 * Activity log database. Optional by hand: the `[[d1_databases]]` block in
		 * wrangler.toml ships commented out, and the worker falls back to the
		 * legacy `log:` KV ring buffer when the binding is absent. Regenerating
		 * this file after uncommenting that block makes it required, which the
		 * worker's `env.DB ? … : …` checks still satisfy.
		 */
		DB?: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
