name = "nythros-mail"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
preview_urls = false

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "fc76f72eceef4fc98e637827c9f7f977"
